# Generated by Django 5.2.1 on 2025-11-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_chatroom_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
