# Generated by Django 5.2.1 on 2025-11-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chatroom_id_alter_chatroom_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
