# Generated by Django 5.2.1 on 2025-11-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_notification_messagereadstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
