# Generated by Django 5.2.1 on 2025-11-15 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='messagereadstatus',
            constraint=models.UniqueConstraint(fields=('user', 'message'), name='unique_message_read_status'),
        ),
    ]
