# Generated by Django 5.2.1 on 2025-11-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_privatechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='display_name',
            field=models.CharField(default='default_room', max_length=255),
            preserve_default=False,
        ),
    ]
