# Generated by Django 5.2.1 on 2025-11-20 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_message_file_alter_message_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='privatechat',
            name='uniqe_private_chatters',
        ),
        migrations.AddConstraint(
            model_name='privatechat',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b'), name='unique_private_chatters'),
        ),
    ]
